server {
  listen 80;
  server_name _;

  location / {
    root /usr/share/nginx/html;
    index index.html;

    try_files $uri $uri/index.html =404;

    # Since we are serving static files, we can enable gzip compression
    # We will be pre-compressing our static files since we care about cpu-cost
    gzip_static on;
    gzip_comp_level 6;
  }

  # Custom 404 page
  error_page 404 /404.html;
  location = /404.html {
    internal;
  }
}