FROM nginx:latest

# Our custom nginx config file
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# Our static website
COPY ./index.html /usr/share/nginx/html/index.html

# Compress all build files with gzip
# But keep original files as well
RUN find . -type f -exec gzip -9 -k \{\} \;