server {
    listen      80;
    server_name _;

    # Use linux sendfile syscall to speed up file transfers
    # and reduce mem & cpu usage
    sendfile            on;
    sendfile_max_chunk  1m;

    # Enable tcp_nopush to optimize network performance
    tcp_nopush on;

    root /usr/share/nginx/html/;

    location / {
        # Try to serve pre-compressed file first, then fall back to regular file
        # to reduce mem & cpu usage
        gzip_static     on;
        gzip_comp_level 6;
    }
}