server {
    listen      80;
    server_name _;

    sendfile            on;
    sendfile_max_chunk  1m;

    root /usr/share/nginx/html/;

    location / {
        gzip_static on;
        gzip_comp_level 6;
    }
}